
export const SPEC_CATEGORIES = {
    BASIC: 'Información Básica',
    WEBSITE: 'Sitio Web Oficial',
    ARCH_VOICE: 'Arquitectura y Voces',
    OSC: 'Sección de Osciladores',
    PERCUSSION: 'Sección de Percusión / Voces',
    FILTER_AMP: 'Filtros y Amplificador',
    ENV_MOD: 'Envolturas y Modulación',
    EFFECTS_PARAMS: 'Parámetros de Efectos',
    SEQUENCER: 'Secuenciador y Memoria',
    CONTROLS_PANEL: 'Controles de Panel (Knobs/Faders)',
    SYSTEM_BUTTONS: 'Botones de Sistema / Funciones',
    CV_GATE: 'CV / Gate y Sincronización',
    INDICATORS: 'Pantalla e Indicadores',
    EFFECTS_CONN: 'Efectos y Conectividad',
    POWER: 'Alimentación y Energía',
    TECH_SPECS: 'Especificaciones Técnicas',
} as const;

export const PREDEFINED_SPECS: Record<string, string[]> = {
    [SPEC_CATEGORIES.BASIC]: [
        'Formato',
        'Tipo de Síntesis',
    ],
    [SPEC_CATEGORIES.ARCH_VOICE]: [
        'Número de Voces (Polifonía)',
        'Tipo de Síntesis',
        'Multitimbralidad',
        'Arquitectura',
        'Partes Multitimbrales',
        'Motores de Síntesis',
        'Memoria Waveforms',
        'Sampler Specs',
        'Kit Slots',
        'Capas por Voz (Layers)',
        'Round Robin',
    ],
    [SPEC_CATEGORIES.OSC]: [
        'Osciladores por Voz',
        'Número de VCOs',
        'Formas de Onda',
        'Rango de Octavas',
        'Sync',
        'FM',
        'Ruido',
        'Número de Wavetables',
        'Frames por Wavetable',
        'Posición WT (Morphing)',
        'Warp Modes',
        'Operadores FM',
        'Algoritmos FM',
        'Parciales',
        'Puntos de Loop (Sampler)',
    ],
    [SPEC_CATEGORIES.PERCUSSION]: [
        'Instrumentos Incluidos',
        'Bass Drum Params',
        'Snare Drum Params',
        'Hi-Hat Params',
        'Percussion Kits',
        'Motores de Percusión',
    ],
    [SPEC_CATEGORIES.FILTER_AMP]: [
        'Tipo de Filtro',
        'Pendiente (Slope)',
        'Resonancia',
        'Overdrive/Distorsión',
        'VCA',
        'Modélado de Filtro',
    ],
    [SPEC_CATEGORIES.ENV_MOD]: [
        'Envolturas (ADSR)',
        'LFOs',
        'Matriz de Modulación',
        'Mod Wheel',
        'Velocity / Aftertouch',
        'Motion Sequences',
    ],
    [SPEC_CATEGORIES.EFFECTS_PARAMS]: [
        'Reverb Params',
        'Delay Params',
        'Chorus/Flanger Params',
        'Distortion/Drive',
        'Compressor/Limiter',
        'Side Chain',
    ],
    [SPEC_CATEGORIES.SEQUENCER]: [
        'Número de Patrones',
        'Pasos por Patrón (Steps)',
        'Pistas del Secuenciador',
        'Modos de Reproducción',
        'Pattern Chain',
        'Real-time Recording',
        'Step Recording',
    ],
    [SPEC_CATEGORIES.CONTROLS_PANEL]: [
        'Knobs / Potenciómetros',
        'Sliders / Faders',
        'Encoders',
        'Ruedas de Pitch/Mod',
        'Telas / Pads',
    ],
    [SPEC_CATEGORIES.SYSTEM_BUTTONS]: [
        'Botones de Función',
        'Botones de Modo',
        'Control de Transporte',
        'Teclado de Pasos',
    ],
    [SPEC_CATEGORIES.CV_GATE]: [
        'CV Input/Output',
        'Gate Input/Output',
        'Trigger In',
        'Clock / Sync In/Out',
        'Rango de Voltaje',
        'V/Oct vs Hz/V',
    ],
    [SPEC_CATEGORIES.INDICATORS]: [
        'Tipo de Pantalla',
        'LEDs de Estado',
        'Medidores (Meters)',
        'Retroiluminación',
    ],
    [SPEC_CATEGORIES.EFFECTS_CONN]: [
        'Efectos Integrados',
        'Salidas de Audio',
        'Entradas Externas',
        'MIDI (IN, OUT, THRU)',
        'USB (Audio/MIDI)',
        'Almacenamiento (SD/USB)',
        'Salida Master',
        'Salida Auriculares',
    ],
    [SPEC_CATEGORIES.POWER]: [
        'Tipo de Alimentación',
        'Baterías / Pilas',
        'USB Power',
        'Adaptador AC',
    ],
    [SPEC_CATEGORIES.TECH_SPECS]: [
        'Alimentación',
        'Consumo',
        'Dimensiones',
        'Peso',
        'Año de Lanzamiento',
        'Accesorios Incluidos',
    ],
};
